[package]
name = "casdesk"
version = "0.1.0"
authors = ["pubnoconst <noconst@email.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.4.1"
dioxus = { version = "0.6.0", features = ["router", "launch"] }
dioxus-free-icons = { version = "0.9", features = ["feather"] }
notify-rust = "4.11.4"
rbase64 = "2.0.3"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

